### ISSUE TITLE
Replace `setcongruence` by `setcongruence!` which modifies the table (but with restrictions) ?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#113]
See https://github.com/oscar-system/GenericCharacterTables.jl/pull/104#discussion_r1691083517

(Of course we can still have `setcongruence` for backwards compatibility, implemented by first copying the table and then modifying & returning the copy).

**Comment by SoongNoonien** [comment]
Ideally, I'd like to have this at the ring level. The new ring (#82) will have a congruence property which could be modified after initialization. Of course there still should be a `setcongruence` method for character tables. But internally this will just issue `setcongruence` for the base ring.

**Comment by SoongNoonien** [comment]
Since #139 this is handled at the ring level. And I don't think `setcongruence!` is a good idea anymore. We are now able to set any congruence which is possible by the CRT and coercion of characters is possible as well. So an unsafe function shouldn't be necessary anymore.

> But internally this will just issue setcongruence for the base ring.

This wasn't even necessary.
