### ISSUE TITLE
Issues with changed return value of `scalar`

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/GenericCharacterTables.jl#88]
At some point before 0.3.0, the return value of `scalar` was changed from 2 to 1 objects.
Some code (e.g. https://github.com/oscar-system/GenericCharacterTables.jl/blob/36c227ece743a6ab3a86c23a0304115ae396d53f/src/Show.jl#L570) still relies on the old behaviour.

Additionally, this change broke https://github.com/oscar-system/Oscar.jl/blob/1870bfd798c8b2edb3a452b9c543924fb5f09219/test/book/cornerstones/groups/genchar.jlcon#L57 in the OSCAR book.

How do we proceed with this?

**Comment by SoongNoonien** [comment]
@fingolfin What do you think about this? I think `print_decomposition` can easily be adapted to the new return value. All the exception checking is now done within `CycloFrac` itself.

**Comment by fingolfin** [comment]
The idea always was that for the book example as printed on paper, we will require GCT 0.2.x; but newer breaking releases such as 0.3.0 can and will change interfaces to be more comfortable. As such I am not overly concerned about such breakage -- instead of adjusting GCT to allow the code example work unchanged, we'll update the book website with additional versions of the example: "This is the GenericCharacterTable example as printed in the book. Click here for a revised version using a much nicer interface for GCT, as announced in the book"

Of course I don't want to break compatibility gratuitously, but here there really is no good alternative.


(Of course the book proofs are still not here, despite Springer's promises; so hypothetically I could even still adjust the book (!) to match GCT 0.3.x behavior...)

**Comment by fingolfin** [comment]
Of course `print_decomposition` should be adjusted to work, and we should add a test to make sure that it works. But the book example also calls `scalar` directly. The hypothetical change to the book would change
```julia-repl
julia> h = tensor!(T,2,2)
9

julia> scalar(T,4,h)
(0, Set(ParameterException{QQPolyRingElem}[(2*n1)//(q - 1) ∈ ℤ]))

julia> print_decomposition(T, h)
[...]

julia> s, e = scalar(T2,6,h); s
1

julia> e
Set{ParameterException{QQPolyRingElem}} with 2 elements:
  (2*n1)//(q - 1) ∈ ℤ
  (3*n1)//(q - 1) ∈ ℤ

```

to something more like this (@SoongNoonien I am not sure anymore writing `a*b` for *tensor* is a good idea -- users might expect it to be the scalar product... perhaps we should instead defined a `tensor` function, and use that everywhere, and then we install it as a method for ⊗ (unicode), and leave `*` undefined)

aaaaanyway, this is how the above might look like now

```julia-repl
julia> h = tensor(T[2], T[2]);

julia> scalar(T[4],h)
0
With exceptions:
  (2*n1)//(q - 1) ∈ ℤ

julia> print_decomposition(T, h)
[...]

julia> scalar(`T2`[6],h)
1
With exceptions:
  (2*n1)//(q - 1) ∈ ℤ
  (3*n1)//(q - 1) ∈ ℤ

```

**Comment by lgoettgens** [comment]
With https://github.com/oscar-system/GenericCharacterTables.jl/pull/91 merged on the backports branch, the we were able to proceed with the AA update in Oscar.

Regarding the version of GCT used in the book, I didn't know anything and couldn't find it in documentation. If keeping it on some 0.2.x and backporting compat things for new AA/Nemo/etc versions to the release-0.2 branch is the preferred solution by the book editors and the confirmable workflows team, that should be documented in the Oscar book test file that loads GCT.jl so that future people know this.
(I don't have any opinion on this, and would say it wouldn't even count if I had one. But I think that this is some decision that should be done by the before mentioned people and then documented at some obvious place)

**Comment by fingolfin** [comment]
The book will require GCT.jl version 0.2.x (and I will try to insert that as a statement when we get to revise the galley proofs). 

The version of the example on the book website will be adjusted to point to the GCT.jl manual for an updated version of the example (to be part of the manual, see PR #104).


As such I believe this issue is resolved.
